apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  nfs:
    server: 10.1.100.32
    path: /vol_K8s_pruebas
  claimRef:
    namespace: httpd-namespace-nautilus
    name: pvc-nfs