apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
  namespace: httpd-service
spec:
  storageClassName: nfs
  volumeName: nfs-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G